#pragma once

#include <format>
#include <stdexcept>
#include <string>
#include <string_view>

namespace exchange {

enum class Language { SimplifiedChinese, English, TraditionalChinese, Japanese };

enum class Message {
    PluginNotReady,
    CommandHelp,
    Balance,
    NoGivePermission,
    PlayerOffline,
    GiveUsage,
    NoMarketPermission,
    GaveExchanger,
    ConsoleHint,
    PlayerFormOnly,
    PlayerClaimOnly,
    AddBalanceUsage,
    InvalidAmount,
    AmountOutOfRange,
    PlayerBalanceNow,
    BalanceAdjusted,
    StatusOk,
    UnknownSubcommand,
    CommandFailed,
    UnexpectedError,
    RecoveryCannotUse,
    RecoveryCannotDrop,
    HologramNotTarget,
    BlockNoItem,
    ObjectEnabled,
    ActivationFailed,
    FrameCanceled,
    WorldNotLoaded,
    FrameReadFailed,
    FrameReading,
    FrameMissing,
    FrameNoItem,
    FrameEnabled,
    FrameActivationFailed,
    ActorNoItem,
    ActorEnabled,
    MarketClosedPreserved,
    MarketRemoved,
    MarketCloseFailed,
    TradePointClosed,
    MatchingOrderGone,
    BookWanted,
    BookForSale,
    TradeTitle,
    CurrentTrade,
    BalanceLabel,
    SellableRequirements,
    TradeOverviewAccount,
    TradeOverviewRequirements,
    ChooseTradeAction,
    DirectBuySubtitle,
    DirectSellSubtitle,
    NoDirectBuy,
    NoDirectSell,
    OpenTradeFailed,
    QuantityInput,
    IntegerPlaceholder,
    UnitPriceInput,
    PricePlaceholder,
    ContinueButton,
    InvalidFormData,
    InputInvalid,
    OpenInputFailed,
    ConfirmTitle,
    QuantityValue,
    UnitPriceValue,
    MarketBuyExplanation,
    MarketSellExplanation,
    ReviewMaximumPayment,
    ReviewExpectedIncome,
    ReviewDirectBuy,
    ReviewDirectSell,
    AdjustQuantity,
    ReenterQuantity,
    AdjustPrice,
    ReenterPrice,
    ConfirmButton,
    EditTradeButton,
    BackActions,
    OpenReviewFailed,
    QuantityRangeInvalid,
    PriceRangeInvalid,
    QuantityField,
    UnitPriceField,
    WholeNumberRange,
    PriceTooLarge,
    PriceStep,
    DeliveryReceived,
    DeliveryReturned,
    DeliveryPending,
    OtherPlayerSelling,
    OtherPlayerBuying,
    OrderNoFill,
    BuyVerb,
    SellVerb,
    OrderSaved,
    OrderPartiallyFilled,
    TradeCompleted,
    OrderEnded,
    TradeFailed,
    OrdersTitle,
    OrdersHeader,
    NoOpenOrders,
    OrderButton,
    BuyColored,
    SellColored,
    OrderCanceled,
    CancelOrderFailed,
    ReadOrdersFailed,
    ClaimedItems,
    ExchangerLore,
    ExchangerMetaFailed,
    ExchangerReceived,
    ReceiptName,
    ReceiptLore,
    HologramWanted,
    HologramForSale,
    TradeActionLimitBuy,
    TradeActionLimitSell,
    TradeActionMarketBuy,
    TradeActionMarketSell,
    TradeActionFallback,
    ItemEmptyText,
    ItemEmpty,
    ItemCountSuffix,
    ItemDeepValue,
    ItemListEntry,
    ItemLabel,
    ItemData,
    NoneValue,
    ItemCustomName,
    ItemLore,
    ItemEnchantments,
    ItemDurabilityDamage,
    ItemRepairCost,
    ItemUnbreakable,
    NoValue,
    YesValue,
    ItemOtherNone,
    ItemOtherHeader,
    ItemOtherMany,
    UnknownEnchantment,
    InventoryInsufficient,
    Count
};

class UserError : public std::runtime_error {
  public:
    using std::runtime_error::runtime_error;
};

[[nodiscard]] Language languageFromLocale(std::string_view locale) noexcept;
[[nodiscard]] std::string_view localeCode(Language language) noexcept;
[[nodiscard]] std::string_view messageText(Language language, Message message) noexcept;
[[nodiscard]] bool translationCatalogComplete() noexcept;
[[nodiscard]] std::string userFacingError(Language language, const std::exception &error);

template <typename... Args> [[nodiscard]] std::string tr(Language language, Message message, Args &&...args) {
    return std::vformat(messageText(language, message), std::make_format_args(args...));
}

} // namespace exchange
